=== sachinkrishna233/XML/validator.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userid">
                                <!-- xml restrictions -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1" />
                                        <xs:maxInclusive value="10" />
                                    </xs:restriction>
                                </xs:simpleType>
                                <!-- end of restrictions -->
                            </xs:element>
                            <xs:element type="xs:string" name="fname" />
                            <xs:element type="xs:string" name="lname" />
                            <xs:element type="xs:string" name="email" />
                            <xs:element type="xs:string" name="password" />
                            <xs:element type="xs:unsignedShort" name="age" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sachinkrishna233/XML/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<!-- Linker for stylesheet -->
<?xml-stylesheet type="text/xsl" href="views.xsl" ?>
<!-- <!DOCTYPE users SYSTEM "elements.dtd">  -->
<!-- xsd linker -->
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validator.xsd">
    <user>
        <userid>1</userid>
        <fname>John</fname>
        <lname>Doe</lname>
        <email>johndoe@mail.com</email>
        <password>christ@123</password>
        <age>21</age>
    </user>
    <user>
        <userid>2</userid>
        <fname>Karina</fname>
        <lname>Vitale</lname>
        <email>vitalekarina@mail.com</email>
        <password>abcdefu</password>
        <age>28</age>
    </user>
    <user>
        <userid>3</userid>
        <fname>Ellis</fname>
        <lname>Dunn</lname>
        <email>Dunn@mail.com</email>
        <password>ElisElis</password>
        <age>37</age>
    </user>
    <user>
        <userid>4</userid>
        <fname>Troy</fname>
        <lname>Benoit</lname>
        <email>troyb@mail.com</email>
        <password>troyous123</password>
        <age>54</age>
    </user>
    <user>
        <userid>5</userid>
        <fname>Kathryn</fname>
        <lname>Browne</lname>
        <email>browny@mail.com</email>
        <password>chocolate</password>
        <age>44</age>
    </user>
    <user>
        <userid>6</userid>
        <fname>Kimberly</fname>
        <lname>Howard</lname>
        <email>howardkim@mail.com</email>
        <password>kimmykim</password>
        <age>25</age>
    </user>
</users>
